### ISSUE TITLE
General Comments/Tracking

### ISSUE THREAD

**Issue by jessica-writes-code** [jmoore523/MSE231-Assignment1#4]
@binghailing 
- [x] Filtered Streaming
- [x] Picture-loading (Make sure it works)
- [x] Make overleaf account
- [x] Write & Edit
- [x] Final Review of Code

@poorna-kumar 
- [x] Filtered Streaming
- [x] Maybe add try/except to filter
- [x] Make Rmd into Overleaf
- [x] Write & Edit
- [ ] Final Review of Code

@jmoore523
- [x] Filtered Streaming
- [x] Repo Hygiene (Rename Files, Update R Code)
- [x] Make overleaf account
- [x] Make plots have same axis range
- [x] Write & Edit
- [x] Final Review of Code

**Comment by jessica-writes-code** [comment]
Hi all -

I've added some writing to the Overleaf document. It's by no means done, so please add/edit as you see fit. Also, I'm not sure how to add footnotes, so I left comments with citations, so that I didn't lose them. Maybe Poorna can show me how to add footnotes appropriately at some point today.

While I was looking at the filtered tweet set, I noticed something interesting that might be an avenue of follow-up. It looks like the coffee-related tweet spikes happen approximately in accordance with the users' time zone -- i.e., EST first, CST second, etc. It's sort of hard to tell, because the data begin and end in the morning PST. If we could get data that start/end in the afternoon or evening, the shifts might be clearer. I'm not sure how @poorna-kumar is doing with the data collection, but I'll try to start a stream this afternoon. Hopefully we'll come up with something and can add it as a tertiary figure to our report.

**Comment by binghailing** [comment]
Just a followup comment to Jessica's comment.  My filtered "coffee" data has been running for almost 36 hours, so we certainly can use that data.  Assuming that we all get the same data, we can probably attach it to the previous data, and take a look at some analyses.  I think I'll stop at 48 hours, so then I'll have covered a Sunday and Monday.  If any of you want to look at the data it's on: corn18: /tmp/bl_tweets_filtered.gz.

**Comment by jessica-writes-code** [comment]
Using that data sounds good to me. Ideally, it might be nice to get two sets of data (filtered and unfiltered) that are during the same 24 (or more) hour period. Do we want to try for that?

**Comment by binghailing** [comment]
I think that's a better idea.  I just hope I don't get more exceptions while running my stream, and we can cover 24 hours simultaneously.

**Comment by jessica-writes-code** [comment]
So, should I start an unfiltered stream now? or do we want to start a filtered & unfiltered one simultaneously at some point?

**Comment by binghailing** [comment]
I think you can start it now, as long as we have overlap data it's fine.  I don't see a particular reason why we need to start both at the same time, as long as both are running at the same time for 24 hours.

**Comment by jessica-writes-code** [comment]
Sounds good. Will do.

**Comment by jessica-writes-code** [comment]
Streaming crashed on corn (because of course it did). Restarting now.

**Comment by binghailing** [comment]
Mine crashed at 3:42 PM, and somehow I caught it.  Restarted within the minute.

**Comment by poorna-kumar** [comment]
Hi guys, 

Sorry for being AWOL today; been slightly preoccupied with some other stuff + career fair prep.

I've modified the figures slightly to include captions and names by which we can refer to them (in the text). I've also modified the text to reflect our newly minted ability to refer to figures by name. B) 

@jmoore523: would you like me to add footnotes, or references? Just let me know, and I will change the material in your comments to whichever one you like. (For reference, there's a .bib file which contains information about references in bibtex format. Footnotes, on the other hand, you can include with the \footnote command. I could show you this when I see you next).

Also, I speed-read through the document, and it looks great! I added a couple of sentences in places; will add more when I do a more thorough reading.

**Comment by jessica-writes-code** [comment]
Cool. Love the cross-references to the figures. Thanks for doing that!

You're right. I meant references, not footnotes. If you're willing to show me, (maybe after we talk to people for MSE on Wednesday?) that's probably best. Then I'll be able to do it myself.

@binghailing My stream still seems to be running. Fingers crossed that it will do that for another 8 hours.

**Comment by jessica-writes-code** [comment]
I've made some edits to the Overleaf document based on the revised figures. Could both of you take a look and make edits/add additional comments as you feel is necessary? (I promise that I have no attachment to anything that's written there -- so if you think it could be better phrased another way or is just unnecessary, absolutely feel free to rewrite or delete it.)

**Comment by jessica-writes-code** [comment]
Hi All -

Happy almost-weekend! 

It would be awesome if everyone could (a) look over/edit/write additional stuff in the Overleaf report and (b) give the code a final once-over. We have to turn in parse_tweets.py, tweet_analysis.R, the report, and the data files (.txt) files. But, it does not seem we need to turn in the gzipped files (which is good, because those would be annoying to get off of corn).

**Comment by poorna-kumar** [comment]
Note on time zones on Twitter:
I've been trying to explore the data a little bit to uncover what additional US time zones there are (in addition to our standard four time zones). So far, in the tweets I've gone through, I've discovered:
1. America/New_York
2. America/Denver
3. America/Detroit
4. America/Chicago
5. America/Los Angeles 
6. Hawaii

I'll collect a few summary statistics about the fraction of these time zones in my data, and maybe we could include a line in our report saying that they exist (and that our trend lines would possibly be different if we accounted for these tweets in one of our four standard time zones). I doubt my explorations will be anything close to exhaustive, but it's worth tacking on a line I guess :)

I also tried to get the complete Twitter list of time zones. When I logged into my own profile, I didn't see some of the time zones that were present in the Twitter data I streamed (leading me to wonder if they've changed the options for time zones at some point). Additionally, some other data I've seen online (lists of Twitter time zones) seem to be different from one another, indicating that either the list of time zones has been changing over time, or that nobody has cared enough to list them properly in the past.

**Comment by binghailing** [comment]
A quick look at the [twitter apps timezones help](https://dev.twitter.com/ads/basics/timezones) shows that the time zones are used from the [tz database](https://en.wikipedia.org/wiki/Tz_database#Names_of_time_zones) which does have a link to a [full list on wikipedia](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) which is probably in flux over time.

This was just from the ads API and not our apps API, which doesn't have much info on the types of timezones that we are going to get.  I don't think we need to worry about the proportion of data that exists in certain time zones outside of the scope of the problem, just to know that it would affect our data.  I probably can write a python script that reads my tweets and spit out a list of unique timezones, if you think that warrants digging into the problem further.

**Comment by poorna-kumar** [comment]
I agree, we don't need to worry. And I don't think we need to dig much deeper than this. Here are my summary stats from the full list of unfiltered tweets: 

Total number of tweets scraped: 5382537
Number of tweets in four US-normalized time zones of interest: 835542
Number of key errors (no data of interest in tweet): 1381373
Number of time zones set to None: 1925680
Number of other US time zones identified: 62817

 The six time zones I found were the only ones that came up in my manual exploration, so I assumed that any others, if they existed, were in a smaller proportion.

**Comment by poorna-kumar** [comment]
The last number I've quoted refers to the number of tweets with other time zones (and not the number of unique time zones).

**Comment by poorna-kumar** [comment]
I've added a line in my script to get the other unique time zones in our data (apart from the four normalized time zones, the extra US time zones I found, and None type time zones). Nothing looked interesting, but I've uploaded the output of the script if you're curious.

**Comment by jessica-writes-code** [comment]
This is really awesome, Poorna. Thanks for digging in and figuring this all out!

Since you did all the leg work, did you want one of us to do the write-up or would you prefer to do it yourself, since you're more familiar with the work that you did?

**Comment by poorna-kumar** [comment]
Don't worry about it -- I'll add stuff to the report. I feel pretty guilty, actually, that I left so much work to you two so far, so I'm just doing what I can to right the balance :)

**Comment by jessica-writes-code** [comment]
Cool. Let us know if you would like any assistance!

**Comment by poorna-kumar** [comment]
I made some changes to the report, and left a couple of comments too.

**Comment by jessica-writes-code** [comment]
Awesome. Your additions look good to me. I've tried to respond to your comments in the document, but if I've missed one, please let me know.

Do we think we'll be finished in time to submit this before class tomorrow?

**Comment by binghailing** [comment]
Just FYI, I made a few code changes and merged it into master early this morning.  I made a pull request and closed it pretty much immediately.  I took a look at Poorna's additions and Jessica's comments just now, and they look good as well.  I'm happy with what we have, and I think we covered it quite thoroughly.

**Comment by poorna-kumar** [comment]
Okay, it looks like there are some instructions on Piazza about the specs of our report, and one of them is that it should not be more than three pages long. So we need to decide what to take out of the report/how to compress it to three pages. Apart from that, it's good to go. I wish they'd let us know earlier, though, about the length restriction.

**Comment by jessica-writes-code** [comment]
Hi all -

I did a little clean up of the language in our report. (I left one comment
at the beginning about something that we could remove, but don't need to.)
Overall, I thought it was pretty tight to begin with.

Also, it turns out you need to muck around with "\textwidth" and the margin
options in order to adjust the amount of text on a line. I did a little of
that, too. At this point we're only mildly over 3pgs (if you don't count
the references). Any additional clean-up would be great, but if you can't
find anything to remove, that's also probably okay.

I'll plan to turn in everything tomorrow before section (so, probably
around 11am). If you need me to hold off, please just say so.
- Jessica

**Comment by poorna-kumar** [comment]
I fiddled with the \textwidth a little more and also decreased some of the whitespace between sections (in the main report, you'll see that I've added some \vspace{} lines). Our text is now exactly three pages, and the references are an additional half page.

@jmoore523: I agreed with your suggestion of removing that line that you'd commented on, so I took it out (initially, I'd planned to tie it to the fraction of tweets that I'd found to be from the US, but didn't end up doing so).

I also made a few minor edits, and changed the section "Plots and Results" to "Methodology and Results". The report looks good to me now (and in my opinion can be submitted), but if you both have any more changes to make, that's fine with me.

**Comment by jessica-writes-code** [comment]
Nice. I took a quick look - I like your formatting edits.

Also, looks good to me. Ready to submit after Binghai's given it his okay.

**Comment by binghailing** [comment]
I only inquired about a deletion of a line.  Everything else looks fine, and I tried to do a bit of condensing in a part where I felt it was overly verbose.

**Comment by jessica-writes-code** [comment]
I'd be okay with deleting that line but I also think it's not doing much
harm where it is, so I'll leave it to Poorna to make the final call (since
I think she wrote it, too).

**Comment by poorna-kumar** [comment]
Oh, which line is this? I thought I deleted the line Jessica had suggested
be removed.

**Comment by jessica-writes-code** [comment]
It's one about the API possibly sampling heavier from PST. I think I may
have written a version of it and then you edited it? (Really, not sure.) I
have no special attachment to the line.

**Comment by poorna-kumar** [comment]
Oh, I just saw Binghai's comment.

I'm not super-attached to that line, so you can remove it. :) I had just
put it there because I thought it might be possible that we were
oversampling West Coast tweets, but I agree that's unlikely and can
probably go away.

**Comment by poorna-kumar** [comment]
Sorry, for some reason I didn't loop Binghai in.

**Comment by jessica-writes-code** [comment]
Alrighty. It's been removed.

**Comment by jessica-writes-code** [comment]
So, it's not abundantly clear from Canvas how we're actually supposed to submit the homework. There's a post regarding this issue on Piazza, so hopefully that will be answered shortly. If not, we can ask in class.

Point being: I haven't submitted our homework yet because it's unclear how to do so.

**Comment by jessica-writes-code** [comment]
Now submitted!

**Comment by poorna-kumar** [comment]
Testing to see whether replying through my email is a valid way of
responding.
